name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader
        working-directory: backend

      - name: Install NPM dependencies for backend
        run: npm install
        working-directory: backend

      - name: Build backend assets
        run: npm run build
        working-directory: backend

      - name: Install NPM dependencies for frontend
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Export frontend
        run: npm run export
        working-directory: frontend

      - name: FTP Deploy Backend
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          server-dir: ${{ secrets.CPANEL_PATH }}
          local-dir: backend/
          port: ${{ secrets.CPANEL_PORT }}

      - name: FTP Deploy Frontend
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          server-dir: ${{ secrets.CPANEL_PATH }}/frontend
          local-dir: frontend/out/
          port: ${{ secrets.CPANEL_PORT }}