<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreOrderRequest;
use App\Models\Order;
use App\Models\Service;
use App\Enums\OrderStatus;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Inertia\Inertia;
use Inertia\Response;

class OrderCreateController extends Controller
{
    /**
     * Show the form for creating a new order.
     */
    public function create(): Response
    {
        $services = Service::system()->active()->ordered()->get();
        $customers = \App\Models\Customer::active()->orderBy('name')->get();

        return Inertia::render('Orders/Create', [
            'services' => $services->map(function ($service) {
                return [
                    'id' => $service->id,
                    'code' => $service->code,
                    'name' => [
                        'en' => $service->getNameEn(),
                        'ar' => $service->getNameAr(),
                    ],
                    'unit_price' => $service->unit_price,
                    'unit' => $service->unit,
                ];
            }),
            'customers' => $customers->map(function ($customer) {
                return [
                    'id' => $customer->id,
                    'name' => $customer->name,
                    'phone' => $customer->phone,
                    'email' => $customer->email,
                    'type' => $customer->type,
                ];
            }),
        ]);
    }

    /**
     * Store a newly created order in storage.
     */
    public function store(StoreOrderRequest $request): RedirectResponse
    {
        $validated = $request->validated();

        try {
            return DB::transaction(function () use ($validated, $request) {
                // Prepare order data
                $orderData = [
                    'customer_id' => $validated['customer_id'],
                    'order_date' => $validated['order_date'] ?? now(),
                    'status' => OrderStatus::PENDING,
                    'subtotal' => $validated['subtotal'] ?? 0,
                    'discount_amount' => $validated['discount'] ?? 0,
                    'tax_amount' => $validated['tax'] ?? 0,
                    'total_amount' => $validated['total'] ?? 0,
                    'user_id' => auth()->id(),
                ];

                // Create order
                $order = Order::create($orderData);

                // Create order items using model (handles JSON automatically)
                foreach ($validated['items'] as $item) {
                    $serviceId = $item['service_id'] ?? null;
                    $serviceName = $item['description'] ?? null;
                    $isCustom = $item['is_custom'] ?? false;

                    // If it's a custom service (no service_id but has name), create it in services table
                    if (!$serviceId && $serviceName) {
                        $service = Service::create([
                            'name' => [
                                'en' => $serviceName,
                                'ar' => $serviceName,
                            ],
                            'unit_price' => $item['unit_price'],
                            'unit' => $item['unit'] ?? '',
                            'is_active' => true,
                            'is_custom' => true,
                            'sort_order' => 0,
                        ]);
                        $serviceId = $service->id;
                    }

                    // Only create item if we have a service_id
                    if ($serviceId) {
                        // Format description as array for translatable field (model will handle JSON conversion)
                        $description = null;
                        if ($serviceName) {
                            $description = [
                                'en' => $serviceName,
                                'ar' => $serviceName,
                            ];
                        }

                        \App\Models\OrderItem::create([
                            'order_id' => $order->id,
                            'service_id' => $serviceId,
                            'description' => $description,
                            'quantity' => $item['quantity'],
                            'unit_price' => $item['unit_price'],
                            'unit' => $item['unit'] ?? 'pcs',
                            'amount' => $item['quantity'] * $item['unit_price'],
                        ]);
                    }
                }

                // Create invoice (invoice_number will be auto-generated by GeneratesUniqueNumber trait)
                $invoice = \App\Models\Invoice::create([
                    'order_id' => $order->id,
                    'customer_id' => $order->customer_id,
                    'user_id' => auth()->id(),
                    'invoice_date' => now(),
                    'due_date' => now()->addDays(30),
                    'total_amount' => $validated['total'] ?? $order->total_amount,
                    'paid_amount' => 0,
                    'status' => \App\Enums\PaymentStatus::DUE,
                ]);

                // Redirect to invoice payment page
                return redirect()->route('invoices.payment', $invoice)
                    ->with('success', 'Order and invoice created successfully.');
            });
        } catch (\Illuminate\Validation\ValidationException $e) {
            // Redirect to create page with validation errors
            return redirect()->route('orders.create')
                ->withErrors($e->validator->errors())
                ->withInput();
        } catch (\Exception $e) {
            Log::error('Order creation failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'request_data' => $request->except(['password', '_token']),
            ]);

            return redirect()->route('orders.create')
                ->with('error', 'Failed to create order: ' . $e->getMessage())
                ->withInput();
        }
    }

    /**
     * Show the preview page for order creation.
     */
    public function createPreview(): Response
    {
        return Inertia::render('Orders/CreatePreview');
    }
}
